/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
**/

/**
 * idea, every third Fibinacci number is even
 * */
#include <stdio.h>

int main(int argc, char** argv)
{
	unsigned int f1=1,f2=1,f3=2, sum=0;
	/**
	while(f3 < 4000000)
	{
		f3=f1+f2;
		sum+=f3 * !(f3%2);
		f1=f2;
		f2=f3;
	}
	**/
  	while(f3 < 4000000)		
	{
		sum+=f3;
		f1=f2+f3;
		f2=f3+f1;
		f3=f1+f2;
	}
	printf("%u\n",sum);
	return 0;
}
